general:
  description: Config for producing data for National PV Inference
  name: national_boost_model
input_data:
  #---------------------- GSP -------------------
  gsp:
    history_minutes: 1440 # 60 x 24
    forecast_minutes: 480
    live_load_extra_minutes: 0
    live_interpolate_minutes: 0
    log_level: "INFO"
    is_live: True

  #---------------------- NWP -------------------
  nwp:
    ukv:
      nwp_channels:
        - dswrf
        - lcc
        - t
        - wdir10
      nwp_zarr_path: !ENV ${NWP_ZARR_PATH}
      history_minutes: 60
      forecast_minutes: 480 # TODO - need 36 hours, not just 12
