name: "xgnational_model"
path_to_uk_region_mask: "data/uk_region_mask.npy"
gsp_data_history: 24
gsp_data_frequency: "30T"
forecast_horizon_hours: [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
  23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
  33, 34, 35, 36]
nwp_variables: ['dswrf', 'hcct', 'lcc', 't', 'sde', 'wdir10']
required_model_covariates: [
    "dswrf_within",
    "dswrf_outer",
    "hcct_within",
    "hcct_outer",
    "lcc_within",
    "lcc_outer",
    "t_within",
    "t_outer",
    "sde_within",
    "sde_outer",
    "wdir10_within",
    "wdir10_outer",
    "dswrf_diff",
    "hcct_diff",
    "lcc_diff",
    "t_diff",
    "sde_diff",
    "wdir10_diff",
    "SIN_MONTH",
    "COS_MONTH",
    "SIN_DAY",
    "COS_DAY",
    "SIN_HOUR",
    "COS_HOUR",
    "PV_LAG_DAY",
    "PV_LAG_1HR",
    "PV_LAG_2HR",
    "ghi",
    "dni",
    "zenith",
    "elevation",
    "azimuth",
    "equation_of_time"]
overwrite_read_datetime_at_inference: True
clip_near_zero_predictions: True
clip_near_zero_value_kw: 50.0