name: Build docker

on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  push_to_registry:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: docker build .