name: Run pytests
on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  call-pytest-test:
    uses: openclimatefix/.github/.github/workflows/python-test.yml@main
    with:
      pytest_cov_dir: gradboost_pv
      test_dir: "tests"
      python-version: "['3.11']"
      os_list: '["ubuntu-latest"]'
      sudo_apt_install: "libgeos++-dev libproj-dev proj-data proj-bin cmake git"
