name: Run pytests
on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  call-pytest-test:
    uses: openclimatefix/.github/.github/workflows/python-test.yml@main
    with:
      pytest_cov_dir: gradboost_pv
      python-version: "['3.10']"
      os_list: '["ubuntu-latest"]'
      sudo_apt_install: "libgeos++-dev libproj-dev proj-data proj-bin cmake git"
      extra_commands: "git clone --recursive https://github.com/dmlc/xgboost && cd xgboost && mkdir build && cd build && cmake .. && make -j4 && cd .. && cd python-package && pip install . ""
